package com.gopal.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.gopal.database.Favorites;
import com.gopal.database.TrackIds;

import com.gopal.database.FavoritesDao;
import com.gopal.database.TrackIdsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig favoritesDaoConfig;
    private final DaoConfig trackIdsDaoConfig;

    private final FavoritesDao favoritesDao;
    private final TrackIdsDao trackIdsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        favoritesDaoConfig = daoConfigMap.get(FavoritesDao.class).clone();
        favoritesDaoConfig.initIdentityScope(type);

        trackIdsDaoConfig = daoConfigMap.get(TrackIdsDao.class).clone();
        trackIdsDaoConfig.initIdentityScope(type);

        favoritesDao = new FavoritesDao(favoritesDaoConfig, this);
        trackIdsDao = new TrackIdsDao(trackIdsDaoConfig, this);

        registerDao(Favorites.class, favoritesDao);
        registerDao(TrackIds.class, trackIdsDao);
    }
    
    public void clear() {
        favoritesDaoConfig.getIdentityScope().clear();
        trackIdsDaoConfig.getIdentityScope().clear();
    }

    public FavoritesDao getFavoritesDao() {
        return favoritesDao;
    }

    public TrackIdsDao getTrackIdsDao() {
        return trackIdsDao;
    }

}
