package com.gopal.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FAVORITES.
 */
public class Favorites {

    private Long id;
    private long trackId;
    private long totalTime;
    /** Not-null value. */
    private String trackName;
    /** Not-null value. */
    private String artiestName;
    /** Not-null value. */
    private String trackCensoredName;
    /** Not-null value. */
    private String songPicUrl;
    /** Not-null value. */
    private String songPreviewUrl;

    public Favorites() {
    }

    public Favorites(Long id) {
        this.id = id;
    }

    public Favorites(Long id, long trackId, long totalTime, String trackName, String artiestName, String trackCensoredName, String songPicUrl, String songPreviewUrl) {
        this.id = id;
        this.trackId = trackId;
        this.totalTime = totalTime;
        this.trackName = trackName;
        this.artiestName = artiestName;
        this.trackCensoredName = trackCensoredName;
        this.songPicUrl = songPicUrl;
        this.songPreviewUrl = songPreviewUrl;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getTrackId() {
        return trackId;
    }

    public void setTrackId(long trackId) {
        this.trackId = trackId;
    }

    public long getTotalTime() {
        return totalTime;
    }

    public void setTotalTime(long totalTime) {
        this.totalTime = totalTime;
    }

    /** Not-null value. */
    public String getTrackName() {
        return trackName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTrackName(String trackName) {
        this.trackName = trackName;
    }

    /** Not-null value. */
    public String getArtiestName() {
        return artiestName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setArtiestName(String artiestName) {
        this.artiestName = artiestName;
    }

    /** Not-null value. */
    public String getTrackCensoredName() {
        return trackCensoredName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTrackCensoredName(String trackCensoredName) {
        this.trackCensoredName = trackCensoredName;
    }

    /** Not-null value. */
    public String getSongPicUrl() {
        return songPicUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSongPicUrl(String songPicUrl) {
        this.songPicUrl = songPicUrl;
    }

    /** Not-null value. */
    public String getSongPreviewUrl() {
        return songPreviewUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSongPreviewUrl(String songPreviewUrl) {
        this.songPreviewUrl = songPreviewUrl;
    }

}
