package com.gopal.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TRACK_IDS.
 */
public class TrackIds {

    private Long id;
    private long trackId;

    public TrackIds() {
    }

    public TrackIds(Long id) {
        this.id = id;
    }

    public TrackIds(Long id, long trackId) {
        this.id = id;
        this.trackId = trackId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getTrackId() {
        return trackId;
    }

    public void setTrackId(long trackId) {
        this.trackId = trackId;
    }

}
